-- Create schema for all api functions and materialized views

CREATE SCHEMA IF NOT exists api;

GRANT ALL ON SCHEMA api TO postgres;

GRANT USAGE ON SCHEMA api TO read_only_all;

GRANT USAGE ON SCHEMA api TO read_only_public;

GRANT USAGE ON SCHEMA api TO read_write_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT SELECT ON TABLES TO read_only_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT SELECT ON TABLES TO read_only_public;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT INSERT, TRIGGER, REFERENCES, TRUNCATE, UPDATE, SELECT ON TABLES TO read_write_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT SELECT ON TABLES TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT SELECT ON TABLES TO read_only_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT REFERENCES, TRUNCATE, UPDATE, SELECT, INSERT, TRIGGER ON TABLES TO read_write_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT SELECT ON TABLES TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT SELECT ON TABLES TO read_only_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT SELECT ON TABLES TO read_only_public;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT REFERENCES, TRUNCATE, UPDATE, SELECT, INSERT, TRIGGER ON TABLES TO read_write_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT SELECT ON TABLES TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT USAGE ON SEQUENCES TO read_only_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT USAGE ON SEQUENCES TO read_only_public;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT ALL ON SEQUENCES TO read_write_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT USAGE ON SEQUENCES TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT USAGE ON SEQUENCES TO read_only_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT USAGE ON SEQUENCES TO read_only_public;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT ALL ON SEQUENCES TO read_write_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT USAGE ON SEQUENCES TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT USAGE ON SEQUENCES TO read_only_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT USAGE ON SEQUENCES TO read_only_public;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT ALL ON SEQUENCES TO read_write_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT USAGE ON SEQUENCES TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT EXECUTE ON FUNCTIONS TO read_only_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT EXECUTE ON FUNCTIONS TO read_only_public;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT EXECUTE ON FUNCTIONS TO read_write_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT EXECUTE ON FUNCTIONS TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT EXECUTE ON FUNCTIONS TO read_only_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT EXECUTE ON FUNCTIONS TO read_only_public;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT EXECUTE ON FUNCTIONS TO read_write_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT EXECUTE ON FUNCTIONS TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT EXECUTE ON FUNCTIONS TO read_only_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT EXECUTE ON FUNCTIONS TO read_only_public;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT EXECUTE ON FUNCTIONS TO read_write_all;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT EXECUTE ON FUNCTIONS TO PUBLIC;